name: Deploy to GCP Cloud Run

on:
  push:
    branches: [deployment]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: eliteentries-algo

    - name: Authenticate Docker with Google Artifact Registry
      run: |
        gcloud auth configure-docker --quiet

    - name: Build and tag Docker image
      run: |
        docker build -t us-docker.pkg.dev/eliteentries-algo/eliteentries/webapp .

    - name: Push Docker image using gcloud
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev
        docker push us-docker.pkg.dev/eliteentries-algo/eliteentries/webapp


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy webapp \
          --image us-docker.pkg.dev/eliteentries-algo/eliteentries/webapp \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
